"""Pre-rendered bridge clips for instant comment responses.

Why: when a viewer comment lands, the LLM + TTS + LatentSync pipeline takes
~8-15s. To kill the dead air, we play a generic acknowledgement clip
("great question, let me check") for the first 2-3s while the real response
renders in the background.

Architecture:
  • Scripts live in BRIDGE_SCRIPTS — short utterances, label-tagged.
  • Pre-renders live in backend/renders/bridges/<label>/<slug>.mp4
  • A manifest.json keeps the (label, script, file, ms) mapping.
  • At runtime, pick_bridge_clip(label) returns a URL ready to play.
  • If no clips available for a label, falls back to "neutral" pool.
  • If THAT pool is empty, returns None and caller skips the bridge.

To populate:
  python -m agents.bridge_clips render --avatar wav2lip256_avatar1
  (requires LatentSync /api/latentsync available on RUNPOD_POD_IP)
"""
from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import logging
import random
import sys
import time
from pathlib import Path
from typing import Any

logger = logging.getLogger("empire.bridge")

RENDER_DIR = Path(__file__).resolve().parent.parent / "renders"
BRIDGE_DIR = RENDER_DIR / "bridges"
MANIFEST_PATH = BRIDGE_DIR / "manifest.json"
BRIDGE_DIR.mkdir(parents=True, exist_ok=True)

# Secondary library: the LatentSync-rendered clips at phase0/assets/clips/.
# These were generated by phase0/scripts/render_generic_clips.py and live
# under a different mount (/clips) than the runtime bridges (/renders/bridges).
# pick_bridge_clip falls back to this library when the runtime manifest is
# empty for a given label.
PHASE0_CLIPS_DIR = (Path(__file__).resolve().parent.parent.parent
                    / "phase0" / "assets" / "clips")
PHASE0_MANIFEST_PATH = PHASE0_CLIPS_DIR / "manifest.json"

# Tertiary library: the Wav2Lip-rendered "_generic" clips at
# backend/local_answers/_generic/. These were generated by
# scripts/render_generic_clips.py — the FAST path that mirrors
# render_local_answers.py. Used for the stage demo's intro_arbitrary +
# bridge_arbitrary labels driven by /api/go_live (G hotkey).
GENERIC_DIR = (Path(__file__).resolve().parent.parent
               / "local_answers" / "_generic")
GENERIC_MANIFEST_PATH = GENERIC_DIR / "manifest.json"

# ── Scripts ──────────────────────────────────────────────────────────────────
# Each entry: (label, text). Labels match the Gemma classifier output:
# "question" | "compliment" | "objection" | "neutral".
# Keep utterances 1.5-3s long — they buy us time, not full responses.
#
# Tagging rationale (Apr 2026):
#   These are the ONE bridge tier that's pre-rendered before any demo and
#   never re-rendered per-product, so they get the eleven_v3 model with
#   inline audio tags ([curious], [warmly], [pauses], etc.). Tags shape
#   the prosody of the words that follow them and unlock the gap between
#   "AI voice reading filler" and "person genuinely reacting in real time."
#
#   Conservative tag density on purpose: every tag adds a small risk of
#   the model mis-interpreting a directive as something to read aloud.
#   We pick one emotional-shape tag at the front of each line and at most
#   one delivery beat ([pauses]) inside. Non-verbal sound effects like
#   [laughs] and [sighs] are deliberately avoided here — they read as a
#   distinct beat the lipsync substrate can't match because the substrate
#   video is one continuous "speaking pose" with no laugh / sigh frames.
#   Save those tags for content where the substrate matches.
#
#   Pair this with `model_id="eleven_v3"` when calling text_to_speech in
#   the render pipeline below. v3 honors the brackets; flash will read
#   them aloud.
BRIDGE_SCRIPTS: list[tuple[str, str]] = [
    # questions — show genuine engagement, not a chatbot ack
    ("question", "[curious] Ooh, great question. [pauses] Let me think about that."),
    ("question", "[warmly] Yeah, that's a good one. Hold on a sec."),
    ("question", "[curious] Mmm, totally fair to ask. One sec..."),
    ("question", "[happily] I love that you asked that — okay, so..."),
    # compliments — actual gratitude, not a polite reflex
    ("compliment", "[happily] Aww, thank you so much!"),
    ("compliment", "[warmly] I appreciate that — seriously, thank you."),
    ("compliment", "[playfully] You're so sweet, thank you!"),
    # objections — empathy first, fact second; v3 nails the pivot
    ("objection", "[reassuring] Totally hear you on that. Here's the thing..."),
    ("objection", "[calm] I get it. Let me actually address that."),
    ("objection", "[warmly] That's fair — here's the real deal."),
    # neutral acks (used as fallback for any label)
    ("neutral", "[softly] Okay, hang on one second..."),
    ("neutral", "[warmly] Yeah, let me show you."),
    ("neutral", "[playfully] Mhm, mhm. Okay so..."),
    ("neutral", "[curious] Right, so..."),
    # ── Stage-demo additions (Step 7 of the TikTok Shop overlay plan) ──
    # intro_arbitrary fires from /api/go_live when the operator presses G
    # on /stage. These need to read as natural live-stream openers — like
    # the speaker just hit "Go Live" and is greeting whoever just joined.
    # Keep them ~1.5-2.5s so the overlay's hearts + viewer count have a
    # beat to land before any product-specific pitch follows.
    ("intro_arbitrary", "[excited] Hey everyone, welcome back to the stream!"),
    ("intro_arbitrary", "[cheerfully] What's up, we are LIVE — so glad you're here."),
    ("intro_arbitrary", "[warmly] Good to see y'all dropping in. [excited] Let's get into it."),
    # bridge_arbitrary covers the 60s when the avatar is buying time
    # while the on-device vision pipeline analyzes the held-up item.
    # Read as the speaker improvising while looking at something.
    ("bridge_arbitrary", "[curious] Alright, let me show you what I picked up today."),
    ("bridge_arbitrary", "[softly] Okay, gonna take a closer look at this one."),
    ("bridge_arbitrary", "[playfully] One sec — getting this into frame for you."),
]


def _slug(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()[:10]


def load_manifest() -> dict[str, list[dict[str, Any]]]:
    """Returns {label: [{script, file, url, ms}, ...]}."""
    if not MANIFEST_PATH.exists():
        return {}
    try:
        return json.loads(MANIFEST_PATH.read_text())
    except Exception as e:
        logger.warning("manifest read failed: %s", e)
        return {}


def save_manifest(manifest: dict[str, list[dict[str, Any]]]):
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2))


# ── Runtime selection ────────────────────────────────────────────────────────


def _load_phase0_manifest() -> dict[str, list[dict[str, Any]]]:
    """Load the secondary phase0 LatentSync manifest. Each entry's URL is
    mapped to /clips/<file> (matching the static mount in main.py)."""
    if not PHASE0_MANIFEST_PATH.exists():
        return {}
    try:
        raw = json.loads(PHASE0_MANIFEST_PATH.read_text())
    except Exception:
        return {}
    out: dict[str, list[dict[str, Any]]] = {}
    for label, entries in (raw or {}).items():
        out[label] = []
        for e in entries:
            file = e.get("file") or ""
            if not file:
                continue
            out[label].append({
                "script": e.get("text", ""),
                "file": file,
                "url": f"/clips/{file}",
                "ms": e.get("ms"),
            })
    return out


def _load_generic_manifest() -> dict[str, list[dict[str, Any]]]:
    """Load the tertiary Wav2Lip "_generic" manifest produced by
    scripts/render_generic_clips.py. Same shape as the primary manifest
    so pick_bridge_clip can treat it uniformly. URLs map to the
    /local_answers static mount in main.py (mounted at backend/local_answers)."""
    if not GENERIC_MANIFEST_PATH.exists():
        return {}
    try:
        raw = json.loads(GENERIC_MANIFEST_PATH.read_text())
    except Exception as e:
        logger.warning("generic manifest read failed: %s", e)
        return {}
    out: dict[str, list[dict[str, Any]]] = {}
    for label, entries in (raw or {}).items():
        if not isinstance(entries, list):
            continue
        out[label] = []
        for e in entries:
            file = e.get("file") or ""
            if not file:
                continue
            # url is stored in the manifest as /local_answers/_generic/<name>.mp4
            # so the existing /local_answers static mount serves it without
            # any extra wiring in main.py.
            url = e.get("url") or f"/local_answers/_generic/{Path(file).name}"
            out[label].append({
                "script": e.get("script") or e.get("text", ""),
                "file": file,
                "url": url,
                "ms": e.get("ms"),
            })
    return out


def pick_bridge_clip(label: str) -> dict[str, Any] | None:
    """Return a random pre-rendered bridge for `label`, falling through
    in priority order:
      1. Primary LatentSync manifest at backend/renders/bridges/manifest.json
         (slow render, highest quality).
      2. Tertiary Wav2Lip manifest at backend/local_answers/_generic/manifest.json
         (fast render, used for the demo's intro_arbitrary + bridge_arbitrary
         labels driven by /api/go_live).
      3. Secondary phase0 LatentSync library (the legacy pre-rendered set).
    Within each tier the requested label is tried first, then "neutral".
    Returns None only if every tier is empty for both label and neutral."""
    primary = load_manifest()
    pool = primary.get(label) or primary.get("neutral") or []
    if pool:
        return random.choice(pool)

    # Tier 2: the fast Wav2Lip _generic library — populated by
    # scripts/render_generic_clips.py. Critical for the stage demo's G
    # hotkey to find an intro clip without requiring a slow LatentSync run.
    tertiary = _load_generic_manifest()
    pool = tertiary.get(label) or tertiary.get("neutral") or []
    if pool:
        return random.choice(pool)

    # Tier 3: the phase0 LatentSync library (legacy set).
    secondary = _load_phase0_manifest()
    pool = secondary.get(label) or secondary.get("neutral") or []
    if pool:
        return random.choice(pool)
    return None


def all_bridges() -> dict[str, list[dict[str, Any]]]:
    return load_manifest()


# ── Pre-render workflow ──────────────────────────────────────────────────────


async def render_all(
    *,
    elevenlabs_voice: str = "Rachel",
    avatar_video: str = "/workspace/state_pitching_pose_speaking_1080p.mp4",
    overwrite: bool = False,
    model_id: str = "eleven_v3",
):
    """Generate TTS for each script, send through LatentSync, save to disk,
    write/update manifest. Idempotent — skips already-rendered clips by
    matching the (script, sha256) slug.

    `model_id` defaults to eleven_v3 because bridges are pre-rendered once
    and re-used across every demo forever. v3 honours the audio tags in
    BRIDGE_SCRIPTS ([curious], [warmly], etc.) which is the entire reason
    these scripts were tagged in the first place. Render time per clip is
    higher than flash but only paid once. Pass model_id="eleven_flash_v2_5"
    if you need to re-render fast (the tags will be read aloud — you'll
    want to strip them from BRIDGE_SCRIPTS first)."""
    from agents.seller import text_to_speech, render_pitch_latentsync

    manifest = load_manifest()
    rendered = 0
    skipped = 0
    failed = 0

    for label, text in BRIDGE_SCRIPTS:
        slug = _slug(text)
        out_dir = BRIDGE_DIR / label
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / f"{slug}.mp4"

        # Skip if already rendered + in manifest
        existing = next(
            (c for c in manifest.get(label, []) if c.get("script") == text and Path(c.get("file", "")).exists()),
            None,
        )
        if existing and not overwrite:
            skipped += 1
            logger.info("[skip] %s/%s already rendered", label, slug)
            continue

        t0 = time.time()
        try:
            logger.info("[tts ] %s/%s [%s] — %s", label, slug, model_id, text)
            audio_b64 = await text_to_speech(text, voice=elevenlabs_voice, model_id=model_id)
            if not audio_b64:
                logger.warning("[fail] no audio for %s", text)
                failed += 1
                continue

            logger.info("[ls  ] %s/%s sending to LatentSync...", label, slug)
            video_url = await render_pitch_latentsync(audio_b64, source_video_path=avatar_video)
            if not video_url:
                logger.warning("[fail] no video for %s", text)
                failed += 1
                continue

            # render_pitch_latentsync returns a /renders/... URL pointing at a saved file.
            # Move/copy into our bridges dir for organisation.
            src_path = RENDER_DIR / Path(video_url).name
            if src_path.exists():
                src_path.rename(out_path)
            else:
                logger.warning("[fail] render file missing: %s", src_path)
                failed += 1
                continue

            ms = int((time.time() - t0) * 1000)
            entry = {
                "script": text,
                "file": str(out_path.relative_to(RENDER_DIR.parent)),
                "url": f"/renders/bridges/{label}/{out_path.name}",
                "ms": ms,
            }
            manifest.setdefault(label, []).append(entry)
            save_manifest(manifest)
            rendered += 1
            logger.info("[ok  ] %s/%s in %dms", label, slug, ms)
        except Exception as e:
            logger.exception("[err ] %s/%s: %s", label, slug, e)
            failed += 1

    logger.info("=" * 60)
    logger.info("bridge render done: rendered=%d skipped=%d failed=%d", rendered, skipped, failed)
    logger.info("manifest at %s", MANIFEST_PATH)
    logger.info("=" * 60)
    return {"rendered": rendered, "skipped": skipped, "failed": failed, "total": len(BRIDGE_SCRIPTS)}


def main():
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="cmd", required=True)

    sub.add_parser("list", help="show registered bridge scripts")

    r = sub.add_parser("render", help="render all bridge clips via TTS + LatentSync")
    r.add_argument("--voice", default="Rachel")
    r.add_argument("--avatar", default="/workspace/state_pitching_pose_speaking_1080p.mp4",
                   help="path to avatar source video on the RunPod")
    r.add_argument("--overwrite", action="store_true")
    r.add_argument("--model", default="eleven_v3",
                   help="ElevenLabs model id. Default eleven_v3 honours audio tags. "
                        "Pass eleven_flash_v2_5 only if you re-strip the tags from BRIDGE_SCRIPTS.")

    sub.add_parser("manifest", help="print current manifest")

    args = parser.parse_args()

    if args.cmd == "list":
        for label, text in BRIDGE_SCRIPTS:
            print(f"  [{label:11}] {text}")
        return

    if args.cmd == "manifest":
        m = load_manifest()
        for label, items in m.items():
            print(f"== {label} ({len(items)} clips)")
            for c in items:
                print(f"   - {c['url']:60} ({c.get('ms', '?')}ms) — {c['script']}")
        return

    if args.cmd == "render":
        # Add backend dir to path so `agents.seller` resolves.
        sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
        result = asyncio.run(render_all(
            elevenlabs_voice=args.voice,
            avatar_video=args.avatar,
            overwrite=args.overwrite,
            model_id=args.model,
        ))
        sys.exit(0 if result["failed"] == 0 else 1)


if __name__ == "__main__":
    main()
